#!/bin/bash
# Script to capture comprehensive TS004F event catalog with guided interaction
# Usage: ./capture_ts004f_events.sh
# This script runs on the HA box and writes events to /share/ha-tools/logs/ts004f-events-capture.log
#
# The script will:
# 1. Start background log capture
# 2. Prompt you to perform 15 different actions on the device
# 3. Allow retry if you don't perform the action correctly
# 4. Inject markers into the log to identify each action
# 5. Test both Mode 1 (primary) and Mode 2 (alternate) operation

LOG_DIR="/share/ha-tools/logs"
LOG_FILE="$LOG_DIR/ts004f-events-capture.log"
LOG_PID=""

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Create log directory if it doesn't exist
mkdir -p "$LOG_DIR"

# Function to inject marker into log file
inject_marker() {
    local marker="$1"
    local timestamp=$(date '+%Y-%m-%dT%H:%M:%S.%N%:z')
    echo "=== $marker === $timestamp" >> "$LOG_FILE"
}

# Function to display section header
section_header() {
    echo ""
    echo -e "${CYAN}=============================================="
    echo -e "  $1"
    echo -e "==============================================${NC}"
    echo ""
}

# Function to display instruction
instruct() {
    echo -e "${YELLOW}→ $1${NC}"
}

# Function to wait for action completion with retry
wait_for_action() {
    local action="$1"
    local attempt=1
    local success=false

    while [ "$success" = false ]; do
        if [ $attempt -gt 1 ]; then
            inject_marker "RETRY #$attempt: $action"
            echo ""
            echo -e "${RED}Retrying action...${NC}"
        else
            inject_marker "ABOUT TO: $action"
        fi

        echo ""
        instruct "$action"
        echo ""
        read -p "Press ENTER after you've performed the action..."
        echo ""

        # Ask if successful
        while true; do
            read -p "Did you successfully perform the action? (y/n): " yn
            case $yn in
                [Yy]* )
                    success=true
                    inject_marker "COMPLETED: $action"
                    if [ $attempt -gt 1 ]; then
                        echo -e "${GREEN}✓ Action completed (attempt #$attempt)${NC}"
                    else
                        echo -e "${GREEN}✓ Action completed${NC}"
                    fi
                    break
                    ;;
                [Nn]* )
                    attempt=$((attempt + 1))
                    break
                    ;;
                * )
                    echo "Please answer y or n."
                    ;;
            esac
        done

        if [ "$success" = true ]; then
            # Brief pause between actions
            sleep 1
        fi
    done
}

# Cleanup function
cleanup() {
    if [ -n "$LOG_PID" ] && kill -0 $LOG_PID 2>/dev/null; then
        echo ""
        echo "Stopping log capture..."
        kill $LOG_PID 2>/dev/null
        wait $LOG_PID 2>/dev/null
    fi

    echo ""
    echo -e "${GREEN}=============================================="
    echo "  LOG CAPTURE COMPLETE"
    echo -e "==============================================${NC}"
    echo ""
    echo "Log file saved to:"
    echo "  $LOG_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Copy log to dev box for analysis"
    echo "  2. Use scripts/ha_get_logs.sh if needed"
    echo ""
    exit
}

# Trap to ensure cleanup on exit
trap cleanup EXIT INT TERM

# Display header
clear
echo -e "${CYAN}=============================================="
echo "  TS004F EVENT CATALOG CAPTURE"
echo -e "==============================================${NC}"
echo ""
echo "This script will guide you through 15 actions"
echo "to catalog all events generated by the device."
echo ""
echo "Log file: $LOG_FILE"
echo ""
echo -e "${YELLOW}IMPORTANT:${NC}"
echo "• If you make a mistake, answer 'n' to retry"
echo "• Try to be consistent with timing/speed"
echo "• The device should start in Mode 1 (default)"
echo ""
read -p "Press ENTER to start log capture..."

# Start log capture in background
echo ""
echo "Starting log capture..."
ha core logs -f 2>&1 | grep TS004F | sed 's/.*TS004F/TS004F/' > "$LOG_FILE" &
LOG_PID=$!
echo -e "${GREEN}Log capture started (PID: $LOG_PID)${NC}"
sleep 2

inject_marker "=== TEST SESSION START ==="

# ============================================
# MODE 1 ACTIONS
# ============================================

section_header "MODE 1: BUTTON ACTIONS"

wait_for_action "Single click the button"
wait_for_action "Double click the button"
wait_for_action "Long press the button (hold 2-3 seconds)"

section_header "MODE 1: ROTATION ACTIONS"

wait_for_action "Rotate RIGHT slowly (~1-2 notches per second)"
wait_for_action "Rotate RIGHT fast (rapid spinning)"
wait_for_action "Rotate LEFT slowly (~1-2 notches per second)"
wait_for_action "Rotate LEFT fast (rapid spinning)"

section_header "MODE 1: PRESS + ROTATE ACTIONS"

wait_for_action "Press and hold button, then rotate RIGHT slowly"
wait_for_action "Press and hold button, then rotate RIGHT fast"
wait_for_action "Press and hold button, then rotate LEFT slowly"
wait_for_action "Press and hold button, then rotate LEFT fast"

# ============================================
# MODE SWITCHING
# ============================================

section_header "MODE SWITCHING: Mode 1 → Mode 2"

wait_for_action "Triple click the button (switches to Mode 2)"

section_header "MODE 2: SAMPLE ACTION"

wait_for_action "Rotate RIGHT slowly (Mode 2 sample)"

section_header "MODE SWITCHING: Mode 2 → Mode 1"

wait_for_action "Triple click the button (switches back to Mode 1)"

section_header "MODE 1: VERIFICATION"

wait_for_action "Rotate RIGHT slowly (verify Mode 1 restored)"

# ============================================
# COMPLETION
# ============================================

inject_marker "=== TEST SESSION END ==="

echo ""
section_header "ALL ACTIONS COMPLETED!"
echo -e "${GREEN}Congratulations! You've captured all 15 actions.${NC}"
echo ""
echo "The log file contains timestamped markers for each action."
echo "This will be used to analyze the event patterns."
echo ""
read -p "Press ENTER to finish..."

# Cleanup will be called by trap
